// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectEQ21 : FmodAudioEffectEQ
{
	public FmodAudioEffectEQ21() : base(NativeName)
	{
	}
	protected FmodAudioEffectEQ21(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectEQ21(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectEQ21([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectEQ21 self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectEQ21 self) => self?._object;
	public static explicit operator FmodAudioEffectEQ21(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffectEQ.PropertyName
	{

	}

	public new class MethodName : FmodAudioEffectEQ.MethodName
	{

	}

	public new class SignalName : FmodAudioEffectEQ.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectEQ21";
}
