// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectPhaser : FmodAudioEffect
{
	public FmodAudioEffectPhaser() : base(NativeName)
	{
	}
	protected FmodAudioEffectPhaser(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectPhaser(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectPhaser([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectPhaser self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectPhaser self) => self?._object;
	public static explicit operator FmodAudioEffectPhaser(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Depth = "depth";
		public static readonly StringName Feedback = "feedback";
		public static readonly StringName RangeMaxHz = "range_max_hz";
		public static readonly StringName RangeMinHz = "range_min_hz";
		public static readonly StringName RateHz = "rate_hz";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetDepth = "set_depth";
		public static readonly StringName GetDepth = "get_depth";
		public static readonly StringName SetFeedback = "set_feedback";
		public static readonly StringName GetFeedback = "get_feedback";
		public static readonly StringName SetRangeMaxHz = "set_range_max_hz";
		public static readonly StringName GetRangeMaxHz = "get_range_max_hz";
		public static readonly StringName SetRangeMinHz = "set_range_min_hz";
		public static readonly StringName GetRangeMinHz = "get_range_min_hz";
		public static readonly StringName SetRateHz = "set_rate_hz";
		public static readonly StringName GetRateHz = "get_rate_hz";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectPhaser";

	#region Properties

	public float Depth
	{
		get => (float)_object.Get(PropertyName.Depth);
		set => _object.Set(PropertyName.Depth, value);
	}

	public float Feedback
	{
		get => (float)_object.Get(PropertyName.Feedback);
		set => _object.Set(PropertyName.Feedback, value);
	}

	public float RangeMaxHz
	{
		get => (float)_object.Get(PropertyName.RangeMaxHz);
		set => _object.Set(PropertyName.RangeMaxHz, value);
	}

	public float RangeMinHz
	{
		get => (float)_object.Get(PropertyName.RangeMinHz);
		set => _object.Set(PropertyName.RangeMinHz, value);
	}

	public float RateHz
	{
		get => (float)_object.Get(PropertyName.RateHz);
		set => _object.Set(PropertyName.RateHz, value);
	}

	#endregion

	#region Methods

	public void SetDepth(float @depth)
	{
		_object.Call(MethodName.SetDepth, @depth);
	}

	public float GetDepth()
	{
		return (float)_object.Call(MethodName.GetDepth);
	}

	public void SetFeedback(float @feedback)
	{
		_object.Call(MethodName.SetFeedback, @feedback);
	}

	public float GetFeedback()
	{
		return (float)_object.Call(MethodName.GetFeedback);
	}

	public void SetRangeMaxHz(float @range_max_hz)
	{
		_object.Call(MethodName.SetRangeMaxHz, @range_max_hz);
	}

	public float GetRangeMaxHz()
	{
		return (float)_object.Call(MethodName.GetRangeMaxHz);
	}

	public void SetRangeMinHz(float @range_min_hz)
	{
		_object.Call(MethodName.SetRangeMinHz, @range_min_hz);
	}

	public float GetRangeMinHz()
	{
		return (float)_object.Call(MethodName.GetRangeMinHz);
	}

	public void SetRateHz(float @rate_hz)
	{
		_object.Call(MethodName.SetRateHz, @rate_hz);
	}

	public float GetRateHz()
	{
		return (float)_object.Call(MethodName.GetRateHz);
	}

	#endregion
}
