// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectEQ6 : FmodAudioEffectEQ
{
	public FmodAudioEffectEQ6() : base(NativeName)
	{
	}
	protected FmodAudioEffectEQ6(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectEQ6(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectEQ6([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectEQ6 self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectEQ6 self) => self?._object;
	public static explicit operator FmodAudioEffectEQ6(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffectEQ.PropertyName
	{

	}

	public new class MethodName : FmodAudioEffectEQ.MethodName
	{

	}

	public new class SignalName : FmodAudioEffectEQ.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectEQ6";
}
