// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodChannelControl
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public FmodChannelControl() : this(NativeName)
	{
	}
	protected FmodChannelControl(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected FmodChannelControl(Variant variant) : this((RefCounted) variant)
	{
	}
	protected FmodChannelControl([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(FmodChannelControl self) => self?._object;
	public static implicit operator Variant(FmodChannelControl self) => self?._object;
	public static explicit operator FmodChannelControl(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Pasued = "pasued";
		public static readonly StringName Pitch = "pitch";
		public static readonly StringName VolumeDb = "volume_db";
		public static readonly StringName VolumeRamp = "volume_ramp";
		public static readonly StringName Mute = "mute";
		public static readonly StringName Gain = "gain";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName ChannelControlIsValid = "channel_control_is_valid";
		public static readonly StringName ChannelControlIsNull = "channel_control_is_null";
		public static readonly StringName IsPlaying = "is_playing";
		public static readonly StringName Stop = "stop";
		public static readonly StringName SetPaused = "set_paused";
		public static readonly StringName GetPaused = "get_paused";
		public static readonly StringName SetMode = "set_mode";
		public static readonly StringName GetMode = "get_mode";
		public static readonly StringName SetPitch = "set_pitch";
		public static readonly StringName GetPitch = "get_pitch";
		public static readonly StringName GetAudibility = "get_audibility";
		public static readonly StringName SetVolumeDb = "set_volume_db";
		public static readonly StringName GetVolumeDb = "get_volume_db";
		public static readonly StringName SetVolumeRamp = "set_volume_ramp";
		public static readonly StringName GetVolumeRamp = "get_volume_ramp";
		public static readonly StringName SetMute = "set_mute";
		public static readonly StringName GetMute = "get_mute";
		public static readonly StringName SetPan = "set_pan";
		public static readonly StringName SetReverbProperties = "set_reverb_properties";
		public static readonly StringName GetReverbProperties = "get_reverb_properties";
		public static readonly StringName SetLowPassGain = "set_low_pass_gain";
		public static readonly StringName GetLowPassGain = "get_low_pass_gain";
		public static readonly StringName AddDsp = "add_dsp";
		public static readonly StringName RemoveDsp = "remove_dsp";
		public static readonly StringName GetNumDsps = "get_num_dsps";
		public static readonly StringName GetDsp = "get_dsp";
		public static readonly StringName SetDspIndex = "set_dsp_index";
		public static readonly StringName GetDspIndex = "get_dsp_index";
		public static readonly StringName GetDspClock = "get_dsp_clock";
		public static readonly StringName SetDelay = "set_delay";
		public static readonly StringName GetDelay = "get_delay";
		public static readonly StringName AddFadePoint = "add_fade_point";
		public static readonly StringName SetFadePointRamp = "set_fade_point_ramp";
		public static readonly StringName RemoveFadePoints = "remove_fade_points";
		public static readonly StringName GetFadePoints = "get_fade_points";
		public static readonly StringName SetCallback = "set_callback";
		public static readonly StringName ClearCallback = "clear_callback";
	}

	public class SignalName : RefCounted.SignalName
	{
		public static readonly StringName CallbackReceived = "callback_received";
	}

	private static readonly StringName NativeName = "FmodChannelControl";

	#region Properties

	public bool Pasued
	{
		get => (bool)_object.Get(PropertyName.Pasued);
		set => _object.Set(PropertyName.Pasued, value);
	}

	public float Pitch
	{
		get => (float)_object.Get(PropertyName.Pitch);
		set => _object.Set(PropertyName.Pitch, value);
	}

	public float VolumeDb
	{
		get => (float)_object.Get(PropertyName.VolumeDb);
		set => _object.Set(PropertyName.VolumeDb, value);
	}

	public bool VolumeRamp
	{
		get => (bool)_object.Get(PropertyName.VolumeRamp);
		set => _object.Set(PropertyName.VolumeRamp, value);
	}

	public bool Mute
	{
		get => (bool)_object.Get(PropertyName.Mute);
		set => _object.Set(PropertyName.Mute, value);
	}

	public float Gain
	{
		get => (float)_object.Get(PropertyName.Gain);
		set => _object.Set(PropertyName.Gain, value);
	}

	#endregion

	#region Methods

	public bool ChannelControlIsValid()
	{
		return (bool)_object.Call(MethodName.ChannelControlIsValid);
	}

	public bool ChannelControlIsNull()
	{
		return (bool)_object.Call(MethodName.ChannelControlIsNull);
	}

	public bool IsPlaying()
	{
		return (bool)_object.Call(MethodName.IsPlaying);
	}

	public void Stop()
	{
		_object.Call(MethodName.Stop);
	}

	public void SetPaused(bool @paused)
	{
		_object.Call(MethodName.SetPaused, @paused);
	}

	public bool GetPaused()
	{
		return (bool)_object.Call(MethodName.GetPaused);
	}

	public void SetMode(FmodSystem.FmodMode @mode)
	{
		_object.Call(MethodName.SetMode, (int)@mode);
	}

	public FmodSystem.FmodMode GetMode()
	{
		return (FmodSystem.FmodMode)(int)_object.Call(MethodName.GetMode);
	}

	public void SetPitch(float @pitch)
	{
		_object.Call(MethodName.SetPitch, @pitch);
	}

	public float GetPitch()
	{
		return (float)_object.Call(MethodName.GetPitch);
	}

	public float GetAudibility()
	{
		return (float)_object.Call(MethodName.GetAudibility);
	}

	public void SetVolumeDb(float @volume)
	{
		_object.Call(MethodName.SetVolumeDb, @volume);
	}

	public float GetVolumeDb()
	{
		return (float)_object.Call(MethodName.GetVolumeDb);
	}

	public void SetVolumeRamp(bool @volume_ramp)
	{
		_object.Call(MethodName.SetVolumeRamp, @volume_ramp);
	}

	public bool GetVolumeRamp()
	{
		return (bool)_object.Call(MethodName.GetVolumeRamp);
	}

	public void SetMute(bool @mute)
	{
		_object.Call(MethodName.SetMute, @mute);
	}

	public bool GetMute()
	{
		return (bool)_object.Call(MethodName.GetMute);
	}

	public void SetPan(float @pan)
	{
		_object.Call(MethodName.SetPan, @pan);
	}

	public void SetReverbProperties(int @instance, float @wet)
	{
		_object.Call(MethodName.SetReverbProperties, @instance, @wet);
	}

	public float GetReverbProperties(int @instance)
	{
		return (float)_object.Call(MethodName.GetReverbProperties, @instance);
	}

	public void SetLowPassGain(float @gain)
	{
		_object.Call(MethodName.SetLowPassGain, @gain);
	}

	public float GetLowPassGain()
	{
		return (float)_object.Call(MethodName.GetLowPassGain);
	}

	public void AddDsp(int @index, FmodDsp @dsp)
	{
		_object.Call(MethodName.AddDsp, @index, @dsp);
	}

	public void RemoveDsp(FmodDsp @dsp)
	{
		_object.Call(MethodName.RemoveDsp, @dsp);
	}

	public int GetNumDsps()
	{
		return (int)_object.Call(MethodName.GetNumDsps);
	}

	public FmodDsp GetDsp(int @index)
	{
		return (FmodDsp)_object.Call(MethodName.GetDsp, @index);
	}

	public void SetDspIndex(FmodDsp @dsp, int @index)
	{
		_object.Call(MethodName.SetDspIndex, @dsp, @index);
	}

	public int GetDspIndex(FmodDsp @dsp)
	{
		return (int)_object.Call(MethodName.GetDspIndex, @dsp);
	}

	public Godot.Collections.Dictionary GetDspClock()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDspClock);
	}

	public void SetDelay(int @start, int @end, bool @stop_channels = true)
	{
		_object.Call(MethodName.SetDelay, @start, @end, @stop_channels);
	}

	public Godot.Collections.Dictionary GetDelay()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDelay);
	}

	public void AddFadePoint(int @dspclock, float @volume)
	{
		_object.Call(MethodName.AddFadePoint, @dspclock, @volume);
	}

	public void SetFadePointRamp(int @dspclock, float @volume)
	{
		_object.Call(MethodName.SetFadePointRamp, @dspclock, @volume);
	}

	public void RemoveFadePoints(int @start, int @end)
	{
		_object.Call(MethodName.RemoveFadePoints, @start, @end);
	}

	public Godot.Collections.Dictionary GetFadePoints()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetFadePoints);
	}

	public void SetCallback()
	{
		_object.Call(MethodName.SetCallback);
	}

	public void ClearCallback()
	{
		_object.Call(MethodName.ClearCallback);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Signals

	public event Action<int> CallbackReceived
	{
		add
		{
			Connect(SignalName.CallbackReceived, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.CallbackReceived, Callable.From(value));
		}
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
