// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectDelay : FmodAudioEffect
{
	public FmodAudioEffectDelay() : base(NativeName)
	{
	}
	protected FmodAudioEffectDelay(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectDelay(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectDelay([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectDelay self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectDelay self) => self?._object;
	public static explicit operator FmodAudioEffectDelay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Dry = "dry";
		public static readonly StringName Tap1Active = "tap1_active";
		public static readonly StringName Tap1DelayMs = "tap1_delay_ms";
		public static readonly StringName Tap1LevelDb = "tap1_level_db";
		public static readonly StringName Tap1Pan = "tap1_pan";
		public static readonly StringName Tap2Active = "tap2_active";
		public static readonly StringName Tap2DelayMs = "tap2_delay_ms";
		public static readonly StringName Tap2LevelDb = "tap2_level_db";
		public static readonly StringName Tap2Pan = "tap2_pan";
		public static readonly StringName FeedbackActive = "feedback_active";
		public static readonly StringName FeedbackDelayMs = "feedback_delay_ms";
		public static readonly StringName FeedbackLevelDb = "feedback_level_db";
		public static readonly StringName FeedbackLowpass = "feedback_lowpass";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetDry = "set_dry";
		public static readonly StringName GetDry = "get_dry";
		public static readonly StringName SetTap1Active = "set_tap1_active";
		public static readonly StringName IsTap1Active = "is_tap1_active";
		public static readonly StringName SetTap1DelayMs = "set_tap1_delay_ms";
		public static readonly StringName GetTap1DelayMs = "get_tap1_delay_ms";
		public static readonly StringName SetTap1LevelDb = "set_tap1_level_db";
		public static readonly StringName GetTap1LevelDb = "get_tap1_level_db";
		public static readonly StringName SetTap1Pan = "set_tap1_pan";
		public static readonly StringName GetTap1Pan = "get_tap1_pan";
		public static readonly StringName SetTap2Active = "set_tap2_active";
		public static readonly StringName IsTap2Active = "is_tap2_active";
		public static readonly StringName SetTap2DelayMs = "set_tap2_delay_ms";
		public static readonly StringName GetTap2DelayMs = "get_tap2_delay_ms";
		public static readonly StringName SetTap2LevelDb = "set_tap2_level_db";
		public static readonly StringName GetTap2LevelDb = "get_tap2_level_db";
		public static readonly StringName SetTap2Pan = "set_tap2_pan";
		public static readonly StringName GetTap2Pan = "get_tap2_pan";
		public static readonly StringName SetFeedbackActive = "set_feedback_active";
		public static readonly StringName IsFeedbackActive = "is_feedback_active";
		public static readonly StringName SetFeedbackDelayMs = "set_feedback_delay_ms";
		public static readonly StringName GetFeedbackDelayMs = "get_feedback_delay_ms";
		public static readonly StringName SetFeedbackLevelDb = "set_feedback_level_db";
		public static readonly StringName GetFeedbackLevelDb = "get_feedback_level_db";
		public static readonly StringName SetFeedbackLowpass = "set_feedback_lowpass";
		public static readonly StringName GetFeedbackLowpass = "get_feedback_lowpass";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectDelay";

	#region Properties

	public float Dry
	{
		get => (float)_object.Get(PropertyName.Dry);
		set => _object.Set(PropertyName.Dry, value);
	}

	public bool Tap1Active
	{
		get => (bool)_object.Get(PropertyName.Tap1Active);
		set => _object.Set(PropertyName.Tap1Active, value);
	}

	public float Tap1DelayMs
	{
		get => (float)_object.Get(PropertyName.Tap1DelayMs);
		set => _object.Set(PropertyName.Tap1DelayMs, value);
	}

	public float Tap1LevelDb
	{
		get => (float)_object.Get(PropertyName.Tap1LevelDb);
		set => _object.Set(PropertyName.Tap1LevelDb, value);
	}

	public float Tap1Pan
	{
		get => (float)_object.Get(PropertyName.Tap1Pan);
		set => _object.Set(PropertyName.Tap1Pan, value);
	}

	public bool Tap2Active
	{
		get => (bool)_object.Get(PropertyName.Tap2Active);
		set => _object.Set(PropertyName.Tap2Active, value);
	}

	public float Tap2DelayMs
	{
		get => (float)_object.Get(PropertyName.Tap2DelayMs);
		set => _object.Set(PropertyName.Tap2DelayMs, value);
	}

	public float Tap2LevelDb
	{
		get => (float)_object.Get(PropertyName.Tap2LevelDb);
		set => _object.Set(PropertyName.Tap2LevelDb, value);
	}

	public float Tap2Pan
	{
		get => (float)_object.Get(PropertyName.Tap2Pan);
		set => _object.Set(PropertyName.Tap2Pan, value);
	}

	public bool FeedbackActive
	{
		get => (bool)_object.Get(PropertyName.FeedbackActive);
		set => _object.Set(PropertyName.FeedbackActive, value);
	}

	public float FeedbackDelayMs
	{
		get => (float)_object.Get(PropertyName.FeedbackDelayMs);
		set => _object.Set(PropertyName.FeedbackDelayMs, value);
	}

	public float FeedbackLevelDb
	{
		get => (float)_object.Get(PropertyName.FeedbackLevelDb);
		set => _object.Set(PropertyName.FeedbackLevelDb, value);
	}

	public float FeedbackLowpass
	{
		get => (float)_object.Get(PropertyName.FeedbackLowpass);
		set => _object.Set(PropertyName.FeedbackLowpass, value);
	}

	#endregion

	#region Methods

	public void SetDry(float @amount)
	{
		_object.Call(MethodName.SetDry, @amount);
	}

	public float GetDry()
	{
		return (float)_object.Call(MethodName.GetDry);
	}

	public void SetTap1Active(bool @active)
	{
		_object.Call(MethodName.SetTap1Active, @active);
	}

	public bool IsTap1Active()
	{
		return (bool)_object.Call(MethodName.IsTap1Active);
	}

	public void SetTap1DelayMs(float @delay_ms)
	{
		_object.Call(MethodName.SetTap1DelayMs, @delay_ms);
	}

	public float GetTap1DelayMs()
	{
		return (float)_object.Call(MethodName.GetTap1DelayMs);
	}

	public void SetTap1LevelDb(float @level_db)
	{
		_object.Call(MethodName.SetTap1LevelDb, @level_db);
	}

	public float GetTap1LevelDb()
	{
		return (float)_object.Call(MethodName.GetTap1LevelDb);
	}

	public void SetTap1Pan(float @pan)
	{
		_object.Call(MethodName.SetTap1Pan, @pan);
	}

	public float GetTap1Pan()
	{
		return (float)_object.Call(MethodName.GetTap1Pan);
	}

	public void SetTap2Active(bool @active)
	{
		_object.Call(MethodName.SetTap2Active, @active);
	}

	public bool IsTap2Active()
	{
		return (bool)_object.Call(MethodName.IsTap2Active);
	}

	public void SetTap2DelayMs(float @delay_ms)
	{
		_object.Call(MethodName.SetTap2DelayMs, @delay_ms);
	}

	public float GetTap2DelayMs()
	{
		return (float)_object.Call(MethodName.GetTap2DelayMs);
	}

	public void SetTap2LevelDb(float @level_db)
	{
		_object.Call(MethodName.SetTap2LevelDb, @level_db);
	}

	public float GetTap2LevelDb()
	{
		return (float)_object.Call(MethodName.GetTap2LevelDb);
	}

	public void SetTap2Pan(float @pan)
	{
		_object.Call(MethodName.SetTap2Pan, @pan);
	}

	public float GetTap2Pan()
	{
		return (float)_object.Call(MethodName.GetTap2Pan);
	}

	public void SetFeedbackActive(bool @active)
	{
		_object.Call(MethodName.SetFeedbackActive, @active);
	}

	public bool IsFeedbackActive()
	{
		return (bool)_object.Call(MethodName.IsFeedbackActive);
	}

	public void SetFeedbackDelayMs(float @delay_ms)
	{
		_object.Call(MethodName.SetFeedbackDelayMs, @delay_ms);
	}

	public float GetFeedbackDelayMs()
	{
		return (float)_object.Call(MethodName.GetFeedbackDelayMs);
	}

	public void SetFeedbackLevelDb(float @level_db)
	{
		_object.Call(MethodName.SetFeedbackLevelDb, @level_db);
	}

	public float GetFeedbackLevelDb()
	{
		return (float)_object.Call(MethodName.GetFeedbackLevelDb);
	}

	public void SetFeedbackLowpass(float @lowpass)
	{
		_object.Call(MethodName.SetFeedbackLowpass, @lowpass);
	}

	public float GetFeedbackLowpass()
	{
		return (float)_object.Call(MethodName.GetFeedbackLowpass);
	}

	#endregion
}
