// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectSpectrumAnalyzer : FmodAudioEffect
{
	public FmodAudioEffectSpectrumAnalyzer() : base(NativeName)
	{
	}
	protected FmodAudioEffectSpectrumAnalyzer(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectSpectrumAnalyzer(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectSpectrumAnalyzer([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectSpectrumAnalyzer self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectSpectrumAnalyzer self) => self?._object;
	public static explicit operator FmodAudioEffectSpectrumAnalyzer(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName BufferLength = "buffer_length";
		public static readonly StringName FftSize = "fft_size";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetBufferLength = "set_buffer_length";
		public static readonly StringName GetBufferLength = "get_buffer_length";
		public static readonly StringName SetFftSize = "set_fft_size";
		public static readonly StringName GetFftSize = "get_fft_size";
		public static readonly StringName GetMagnitudeForFrequencyRange = "get_magnitude_for_frequency_range";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectSpectrumAnalyzer";

	#region Enums

	public enum FFTSizeEnum : long
	{
		_256 = 0L,
		_512 = 1L,
		_1024 = 2L,
		_2048 = 3L,
		_4096 = 4L,
		Max = 5L,
	}

	public enum MagnitudeMode : long
	{
		Average = 0L,
		Max = 1L,
	}

	#endregion

	#region Properties

	public float BufferLength
	{
		get => (float)_object.Get(PropertyName.BufferLength);
		set => _object.Set(PropertyName.BufferLength, value);
	}

	public FmodAudioEffectSpectrumAnalyzer.FFTSizeEnum FftSize
	{
		get => (FmodAudioEffectSpectrumAnalyzer.FFTSizeEnum)(int)_object.Get(PropertyName.FftSize);
		set => _object.Set(PropertyName.FftSize, (int)value);
	}

	#endregion

	#region Methods

	public void SetBufferLength(float @buffer_length)
	{
		_object.Call(MethodName.SetBufferLength, @buffer_length);
	}

	public float GetBufferLength()
	{
		return (float)_object.Call(MethodName.GetBufferLength);
	}

	public void SetFftSize(FmodAudioEffectSpectrumAnalyzer.FFTSizeEnum @fft_size)
	{
		_object.Call(MethodName.SetFftSize, (int)@fft_size);
	}

	public FmodAudioEffectSpectrumAnalyzer.FFTSizeEnum GetFftSize()
	{
		return (FmodAudioEffectSpectrumAnalyzer.FFTSizeEnum)(int)_object.Call(MethodName.GetFftSize);
	}

	public Godot.Vector2 GetMagnitudeForFrequencyRange(float @begin, float @end, FmodAudioEffectSpectrumAnalyzer.MagnitudeMode @mode = (FmodAudioEffectSpectrumAnalyzer.MagnitudeMode)1)
	{
		return (Godot.Vector2)_object.Call(MethodName.GetMagnitudeForFrequencyRange, @begin, @end, (int)@mode);
	}

	#endregion
}
