// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectCompressor : FmodAudioEffect
{
	public FmodAudioEffectCompressor() : base(NativeName)
	{
	}
	protected FmodAudioEffectCompressor(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectCompressor(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectCompressor([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectCompressor self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectCompressor self) => self?._object;
	public static explicit operator FmodAudioEffectCompressor(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName ThresholdDb = "threshold_db";
		public static readonly StringName Ratio = "ratio";
		public static readonly StringName GainDb = "gain_db";
		public static readonly StringName AttackUs = "attack_us";
		public static readonly StringName ReleaseMs = "release_ms";
		public static readonly StringName Mix = "mix";
		public static readonly StringName Sidechain = "sidechain";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetThreshold = "set_threshold";
		public static readonly StringName GetThreshold = "get_threshold";
		public static readonly StringName SetRatio = "set_ratio";
		public static readonly StringName GetRatio = "get_ratio";
		public static readonly StringName SetGain = "set_gain";
		public static readonly StringName GetGain = "get_gain";
		public static readonly StringName SetAttackUs = "set_attack_us";
		public static readonly StringName GetAttackUs = "get_attack_us";
		public static readonly StringName SetReleaseMs = "set_release_ms";
		public static readonly StringName GetReleaseMs = "get_release_ms";
		public static readonly StringName SetMix = "set_mix";
		public static readonly StringName GetMix = "get_mix";
		public static readonly StringName SetSidechain = "set_sidechain";
		public static readonly StringName GetSidechain = "get_sidechain";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectCompressor";

	#region Properties

	public float ThresholdDb
	{
		get => (float)_object.Get(PropertyName.ThresholdDb);
		set => _object.Set(PropertyName.ThresholdDb, value);
	}

	public float Ratio
	{
		get => (float)_object.Get(PropertyName.Ratio);
		set => _object.Set(PropertyName.Ratio, value);
	}

	public float GainDb
	{
		get => (float)_object.Get(PropertyName.GainDb);
		set => _object.Set(PropertyName.GainDb, value);
	}

	public float AttackUs
	{
		get => (float)_object.Get(PropertyName.AttackUs);
		set => _object.Set(PropertyName.AttackUs, value);
	}

	public float ReleaseMs
	{
		get => (float)_object.Get(PropertyName.ReleaseMs);
		set => _object.Set(PropertyName.ReleaseMs, value);
	}

	public float Mix
	{
		get => (float)_object.Get(PropertyName.Mix);
		set => _object.Set(PropertyName.Mix, value);
	}

	public Godot.StringName Sidechain
	{
		get => (Godot.StringName)_object.Get(PropertyName.Sidechain);
		set => _object.Set(PropertyName.Sidechain, value);
	}

	#endregion

	#region Methods

	public void SetThreshold(float @threshold_db)
	{
		_object.Call(MethodName.SetThreshold, @threshold_db);
	}

	public float GetThreshold()
	{
		return (float)_object.Call(MethodName.GetThreshold);
	}

	public void SetRatio(float @ratio)
	{
		_object.Call(MethodName.SetRatio, @ratio);
	}

	public float GetRatio()
	{
		return (float)_object.Call(MethodName.GetRatio);
	}

	public void SetGain(float @gain_db)
	{
		_object.Call(MethodName.SetGain, @gain_db);
	}

	public float GetGain()
	{
		return (float)_object.Call(MethodName.GetGain);
	}

	public void SetAttackUs(float @attack_us)
	{
		_object.Call(MethodName.SetAttackUs, @attack_us);
	}

	public float GetAttackUs()
	{
		return (float)_object.Call(MethodName.GetAttackUs);
	}

	public void SetReleaseMs(float @release_ms)
	{
		_object.Call(MethodName.SetReleaseMs, @release_ms);
	}

	public float GetReleaseMs()
	{
		return (float)_object.Call(MethodName.GetReleaseMs);
	}

	public void SetMix(float @mix)
	{
		_object.Call(MethodName.SetMix, @mix);
	}

	public float GetMix()
	{
		return (float)_object.Call(MethodName.GetMix);
	}

	public void SetSidechain(Godot.StringName @sidechain)
	{
		_object.Call(MethodName.SetSidechain, @sidechain);
	}

	public Godot.StringName GetSidechain()
	{
		return (Godot.StringName)_object.Call(MethodName.GetSidechain);
	}

	#endregion
}
