// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectRecord : FmodAudioEffect
{
	public FmodAudioEffectRecord() : base(NativeName)
	{
	}
	protected FmodAudioEffectRecord(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectRecord(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectRecord([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectRecord self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectRecord self) => self?._object;
	public static explicit operator FmodAudioEffectRecord(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Format = "format";
		public static readonly StringName RecordingActive = "recording_active";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetRecordingActive = "set_recording_active";
		public static readonly StringName IsRecordingActive = "is_recording_active";
		public static readonly StringName SetFormat = "set_format";
		public static readonly StringName GetFormat = "get_format";
		public static readonly StringName GetRecording = "get_recording";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectRecord";

	#region Enums

	public enum FormatEnum : long
	{
		_8Bits = 0L,
		_16Bits = 1L,
		IMAADPCM = 2L,
	}

	#endregion

	#region Properties

	public FmodAudioEffectRecord.FormatEnum Format
	{
		get => (FmodAudioEffectRecord.FormatEnum)(int)_object.Get(PropertyName.Format);
		set => _object.Set(PropertyName.Format, (int)value);
	}

	public bool RecordingActive
	{
		get => (bool)_object.Get(PropertyName.RecordingActive);
		set => _object.Set(PropertyName.RecordingActive, value);
	}

	#endregion

	#region Methods

	public void SetRecordingActive(bool @record)
	{
		_object.Call(MethodName.SetRecordingActive, @record);
	}

	public bool IsRecordingActive()
	{
		return (bool)_object.Call(MethodName.IsRecordingActive);
	}

	public void SetFormat(FmodAudioEffectRecord.FormatEnum @format)
	{
		_object.Call(MethodName.SetFormat, (int)@format);
	}

	public FmodAudioEffectRecord.FormatEnum GetFormat()
	{
		return (FmodAudioEffectRecord.FormatEnum)(int)_object.Call(MethodName.GetFormat);
	}

	public AudioStreamWav GetRecording()
	{
		return (AudioStreamWav)_object.Call(MethodName.GetRecording);
	}

	#endregion
}
