// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectChorus : FmodAudioEffect
{
	public FmodAudioEffectChorus() : base(NativeName)
	{
	}
	protected FmodAudioEffectChorus(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectChorus(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectChorus([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectChorus self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectChorus self) => self?._object;
	public static explicit operator FmodAudioEffectChorus(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName VoiceCount = "voice_count";
		public static readonly StringName Wet = "wet";
		public static readonly StringName Dry = "dry";
		public static readonly StringName Voice_1_DelayMs = "voice/1/delay_ms";
		public static readonly StringName Voice_2_DelayMs = "voice/2/delay_ms";
		public static readonly StringName Voice_3_DelayMs = "voice/3/delay_ms";
		public static readonly StringName Voice_4_DelayMs = "voice/4/delay_ms";
		public static readonly StringName Voice_1_RateHz = "voice/1/rate_hz";
		public static readonly StringName Voice_2_RateHz = "voice/2/rate_hz";
		public static readonly StringName Voice_3_RateHz = "voice/3/rate_hz";
		public static readonly StringName Voice_4_RateHz = "voice/4/rate_hz";
		public static readonly StringName Voice_1_DepthMs = "voice/1/depth_ms";
		public static readonly StringName Voice_2_DepthMs = "voice/2/depth_ms";
		public static readonly StringName Voice_3_DepthMs = "voice/3/depth_ms";
		public static readonly StringName Voice_4_DepthMs = "voice/4/depth_ms";
		public static readonly StringName Voice_1_LevelDb = "voice/1/level_db";
		public static readonly StringName Voice_2_LevelDb = "voice/2/level_db";
		public static readonly StringName Voice_3_LevelDb = "voice/3/level_db";
		public static readonly StringName Voice_4_LevelDb = "voice/4/level_db";
		public static readonly StringName Voice_1_CutoffHz = "voice/1/cutoff_hz";
		public static readonly StringName Voice_2_CutoffHz = "voice/2/cutoff_hz";
		public static readonly StringName Voice_3_CutoffHz = "voice/3/cutoff_hz";
		public static readonly StringName Voice_4_CutoffHz = "voice/4/cutoff_hz";
		public static readonly StringName Voice_1_Pan = "voice/1/pan";
		public static readonly StringName Voice_2_Pan = "voice/2/pan";
		public static readonly StringName Voice_3_Pan = "voice/3/pan";
		public static readonly StringName Voice_4_Pan = "voice/4/pan";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetVoiceCount = "set_voice_count";
		public static readonly StringName GetVoiceCount = "get_voice_count";
		public static readonly StringName SetWet = "set_wet";
		public static readonly StringName GetWet = "get_wet";
		public static readonly StringName SetDry = "set_dry";
		public static readonly StringName GetDry = "get_dry";
		public static readonly StringName SetVoiceDelayMs = "set_voice_delay_ms";
		public static readonly StringName GetVoiceDelayMs = "get_voice_delay_ms";
		public static readonly StringName SetVoiceRateHz = "set_voice_rate_hz";
		public static readonly StringName GetVoiceRateHz = "get_voice_rate_hz";
		public static readonly StringName SetVoiceDepthMs = "set_voice_depth_ms";
		public static readonly StringName GetVoiceDepthMs = "get_voice_depth_ms";
		public static readonly StringName SetVoiceLevelDb = "set_voice_level_db";
		public static readonly StringName GetVoiceLevelDb = "get_voice_level_db";
		public static readonly StringName SetVoiceCutoffHz = "set_voice_cutoff_hz";
		public static readonly StringName GetVoiceCutoffHz = "get_voice_cutoff_hz";
		public static readonly StringName SetVoicePan = "set_voice_pan";
		public static readonly StringName GetVoicePan = "get_voice_pan";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectChorus";

	#region Properties

	public int VoiceCount
	{
		get => (int)_object.Get(PropertyName.VoiceCount);
		set => _object.Set(PropertyName.VoiceCount, value);
	}

	public float Wet
	{
		get => (float)_object.Get(PropertyName.Wet);
		set => _object.Set(PropertyName.Wet, value);
	}

	public float Dry
	{
		get => (float)_object.Get(PropertyName.Dry);
		set => _object.Set(PropertyName.Dry, value);
	}

	public float Voice_1_DelayMs
	{
		get => (float)_object.Get(PropertyName.Voice_1_DelayMs);
		set => _object.Set(PropertyName.Voice_1_DelayMs, value);
	}

	public float Voice_2_DelayMs
	{
		get => (float)_object.Get(PropertyName.Voice_2_DelayMs);
		set => _object.Set(PropertyName.Voice_2_DelayMs, value);
	}

	public float Voice_3_DelayMs
	{
		get => (float)_object.Get(PropertyName.Voice_3_DelayMs);
		set => _object.Set(PropertyName.Voice_3_DelayMs, value);
	}

	public float Voice_4_DelayMs
	{
		get => (float)_object.Get(PropertyName.Voice_4_DelayMs);
		set => _object.Set(PropertyName.Voice_4_DelayMs, value);
	}

	public float Voice_1_RateHz
	{
		get => (float)_object.Get(PropertyName.Voice_1_RateHz);
		set => _object.Set(PropertyName.Voice_1_RateHz, value);
	}

	public float Voice_2_RateHz
	{
		get => (float)_object.Get(PropertyName.Voice_2_RateHz);
		set => _object.Set(PropertyName.Voice_2_RateHz, value);
	}

	public float Voice_3_RateHz
	{
		get => (float)_object.Get(PropertyName.Voice_3_RateHz);
		set => _object.Set(PropertyName.Voice_3_RateHz, value);
	}

	public float Voice_4_RateHz
	{
		get => (float)_object.Get(PropertyName.Voice_4_RateHz);
		set => _object.Set(PropertyName.Voice_4_RateHz, value);
	}

	public float Voice_1_DepthMs
	{
		get => (float)_object.Get(PropertyName.Voice_1_DepthMs);
		set => _object.Set(PropertyName.Voice_1_DepthMs, value);
	}

	public float Voice_2_DepthMs
	{
		get => (float)_object.Get(PropertyName.Voice_2_DepthMs);
		set => _object.Set(PropertyName.Voice_2_DepthMs, value);
	}

	public float Voice_3_DepthMs
	{
		get => (float)_object.Get(PropertyName.Voice_3_DepthMs);
		set => _object.Set(PropertyName.Voice_3_DepthMs, value);
	}

	public float Voice_4_DepthMs
	{
		get => (float)_object.Get(PropertyName.Voice_4_DepthMs);
		set => _object.Set(PropertyName.Voice_4_DepthMs, value);
	}

	public float Voice_1_LevelDb
	{
		get => (float)_object.Get(PropertyName.Voice_1_LevelDb);
		set => _object.Set(PropertyName.Voice_1_LevelDb, value);
	}

	public float Voice_2_LevelDb
	{
		get => (float)_object.Get(PropertyName.Voice_2_LevelDb);
		set => _object.Set(PropertyName.Voice_2_LevelDb, value);
	}

	public float Voice_3_LevelDb
	{
		get => (float)_object.Get(PropertyName.Voice_3_LevelDb);
		set => _object.Set(PropertyName.Voice_3_LevelDb, value);
	}

	public float Voice_4_LevelDb
	{
		get => (float)_object.Get(PropertyName.Voice_4_LevelDb);
		set => _object.Set(PropertyName.Voice_4_LevelDb, value);
	}

	public float Voice_1_CutoffHz
	{
		get => (float)_object.Get(PropertyName.Voice_1_CutoffHz);
		set => _object.Set(PropertyName.Voice_1_CutoffHz, value);
	}

	public float Voice_2_CutoffHz
	{
		get => (float)_object.Get(PropertyName.Voice_2_CutoffHz);
		set => _object.Set(PropertyName.Voice_2_CutoffHz, value);
	}

	public float Voice_3_CutoffHz
	{
		get => (float)_object.Get(PropertyName.Voice_3_CutoffHz);
		set => _object.Set(PropertyName.Voice_3_CutoffHz, value);
	}

	public float Voice_4_CutoffHz
	{
		get => (float)_object.Get(PropertyName.Voice_4_CutoffHz);
		set => _object.Set(PropertyName.Voice_4_CutoffHz, value);
	}

	public float Voice_1_Pan
	{
		get => (float)_object.Get(PropertyName.Voice_1_Pan);
		set => _object.Set(PropertyName.Voice_1_Pan, value);
	}

	public float Voice_2_Pan
	{
		get => (float)_object.Get(PropertyName.Voice_2_Pan);
		set => _object.Set(PropertyName.Voice_2_Pan, value);
	}

	public float Voice_3_Pan
	{
		get => (float)_object.Get(PropertyName.Voice_3_Pan);
		set => _object.Set(PropertyName.Voice_3_Pan, value);
	}

	public float Voice_4_Pan
	{
		get => (float)_object.Get(PropertyName.Voice_4_Pan);
		set => _object.Set(PropertyName.Voice_4_Pan, value);
	}

	#endregion

	#region Methods

	public void SetVoiceCount(int @voices)
	{
		_object.Call(MethodName.SetVoiceCount, @voices);
	}

	public int GetVoiceCount()
	{
		return (int)_object.Call(MethodName.GetVoiceCount);
	}

	public void SetWet(float @amount)
	{
		_object.Call(MethodName.SetWet, @amount);
	}

	public float GetWet()
	{
		return (float)_object.Call(MethodName.GetWet);
	}

	public void SetDry(float @amount)
	{
		_object.Call(MethodName.SetDry, @amount);
	}

	public float GetDry()
	{
		return (float)_object.Call(MethodName.GetDry);
	}

	public void SetVoiceDelayMs(int @voice_idx, float @delay_ms)
	{
		_object.Call(MethodName.SetVoiceDelayMs, @voice_idx, @delay_ms);
	}

	public float GetVoiceDelayMs(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoiceDelayMs, @voice_idx);
	}

	public void SetVoiceRateHz(int @voice_idx, float @rate_hz)
	{
		_object.Call(MethodName.SetVoiceRateHz, @voice_idx, @rate_hz);
	}

	public float GetVoiceRateHz(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoiceRateHz, @voice_idx);
	}

	public void SetVoiceDepthMs(int @voice_idx, float @depth_ms)
	{
		_object.Call(MethodName.SetVoiceDepthMs, @voice_idx, @depth_ms);
	}

	public float GetVoiceDepthMs(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoiceDepthMs, @voice_idx);
	}

	public void SetVoiceLevelDb(int @voice_idx, float @level_db)
	{
		_object.Call(MethodName.SetVoiceLevelDb, @voice_idx, @level_db);
	}

	public float GetVoiceLevelDb(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoiceLevelDb, @voice_idx);
	}

	public void SetVoiceCutoffHz(int @voice_idx, float @cutoff_hz)
	{
		_object.Call(MethodName.SetVoiceCutoffHz, @voice_idx, @cutoff_hz);
	}

	public float GetVoiceCutoffHz(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoiceCutoffHz, @voice_idx);
	}

	public void SetVoicePan(int @voice_idx, float @pan)
	{
		_object.Call(MethodName.SetVoicePan, @voice_idx, @pan);
	}

	public float GetVoicePan(int @voice_idx)
	{
		return (float)_object.Call(MethodName.GetVoicePan, @voice_idx);
	}

	#endregion
}
