// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectEQ : FmodAudioEffect
{
	public FmodAudioEffectEQ() : base(NativeName)
	{
	}
	protected FmodAudioEffectEQ(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectEQ(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectEQ([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectEQ self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectEQ self) => self?._object;
	public static explicit operator FmodAudioEffectEQ(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Preset = "preset";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetPreset = "set_preset";
		public static readonly StringName GetPreset = "get_preset";
		public static readonly StringName GetBandCount = "get_band_count";
		public static readonly StringName SetBandGainDb = "set_band_gain_db";
		public static readonly StringName GetBandGainDb = "get_band_gain_db";
		public static readonly StringName SetBandFrequency = "set_band_frequency";
		public static readonly StringName GetBandFrequency = "get_band_frequency";
		public static readonly StringName SetBandFilterType = "set_band_filter_type";
		public static readonly StringName GetBandFilterType = "get_band_filter_type";
		public static readonly StringName SetBandQ = "set_band_q";
		public static readonly StringName GetBandQ = "get_band_q";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectEQ";

	#region Enums

	public enum PresetEnum : long
	{
		_6Bands = 0L,
		_10Bands = 1L,
		_21Bands = 2L,
	}

	public enum FilterType : long
	{
		Disabled = 0L,
		Lowpass12dB = 1L,
		Lowpass24dB = 2L,
		Lowpass48dB = 3L,
		Highpass12dB = 4L,
		Highpass24dB = 5L,
		Highpass48dB = 6L,
		Lowshelf = 7L,
		Highshelf = 8L,
		Peaking = 9L,
		Bandpass = 10L,
		Notch = 11L,
		Allpass = 12L,
		Lowpass6db = 13L,
		Highpass6db = 14L,
	}

	#endregion

	#region Properties

	public FmodAudioEffectEQ.PresetEnum Preset
	{
		get => (FmodAudioEffectEQ.PresetEnum)(int)_object.Get(PropertyName.Preset);
		set => _object.Set(PropertyName.Preset, (int)value);
	}

	#endregion

	#region Methods

	public void SetPreset(FmodAudioEffectEQ.PresetEnum @preset)
	{
		_object.Call(MethodName.SetPreset, (int)@preset);
	}

	public FmodAudioEffectEQ.PresetEnum GetPreset()
	{
		return (FmodAudioEffectEQ.PresetEnum)(int)_object.Call(MethodName.GetPreset);
	}

	public int GetBandCount()
	{
		return (int)_object.Call(MethodName.GetBandCount);
	}

	public void SetBandGainDb(int @band_idx, float @gain_db)
	{
		_object.Call(MethodName.SetBandGainDb, @band_idx, @gain_db);
	}

	public float GetBandGainDb(int @band_idx)
	{
		return (float)_object.Call(MethodName.GetBandGainDb, @band_idx);
	}

	public void SetBandFrequency(int @band_idx, float @frequency)
	{
		_object.Call(MethodName.SetBandFrequency, @band_idx, @frequency);
	}

	public float GetBandFrequency(int @band_idx)
	{
		return (float)_object.Call(MethodName.GetBandFrequency, @band_idx);
	}

	public void SetBandFilterType(int @band_idx, FmodAudioEffectEQ.FilterType @filter_type)
	{
		_object.Call(MethodName.SetBandFilterType, @band_idx, (int)@filter_type);
	}

	public FmodAudioEffectEQ.FilterType GetBandFilterType(int @band_idx)
	{
		return (FmodAudioEffectEQ.FilterType)(int)_object.Call(MethodName.GetBandFilterType, @band_idx);
	}

	public void SetBandQ(int @band_idx, float @q)
	{
		_object.Call(MethodName.SetBandQ, @band_idx, @q);
	}

	public float GetBandQ(int @band_idx)
	{
		return (float)_object.Call(MethodName.GetBandQ, @band_idx);
	}

	#endregion
}
