// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodSystem
{
	// Engine object used for calling engine methods
	protected Object _object;

	public FmodSystem() : this(NativeName)
	{
	}
	protected FmodSystem(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected FmodSystem(Variant variant) : this((Object) variant)
	{
	}
	protected FmodSystem([NotNull] Object @object)
	{
		_object = @object;
	}

	public static implicit operator Object(FmodSystem self) => self?._object;
	public static implicit operator Variant(FmodSystem self) => self?._object;
	public static explicit operator FmodSystem(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Object.PropertyName
	{

	}

	public class MethodName : Object.MethodName
	{
		public static readonly StringName SystemIsValid = "system_is_valid";
		public static readonly StringName SystemIsNull = "system_is_null";
		public static readonly StringName CreateSystem = "create_system";
		public static readonly StringName Init = "init";
		public static readonly StringName Close = "close";
		public static readonly StringName Release = "release";
		public static readonly StringName Update = "update";
		public static readonly StringName MixerSuspend = "mixer_suspend";
		public static readonly StringName MixerResume = "mixer_resume";
		public static readonly StringName SetOutput = "set_output";
		public static readonly StringName GetOutput = "get_output";
		public static readonly StringName GetNumDrivers = "get_num_drivers";
		public static readonly StringName GetDriverInfo = "get_driver_info";
		public static readonly StringName SetDriver = "set_driver";
		public static readonly StringName GetDriver = "get_driver";
		public static readonly StringName SetNetworkProxy = "set_network_proxy";
		public static readonly StringName GetNetworkProxy = "get_network_proxy";
		public static readonly StringName SetNetworkTimeout = "set_network_timeout";
		public static readonly StringName GetNetworkTimeout = "get_network_timeout";
		public static readonly StringName GetVersion = "get_version";
		public static readonly StringName GetOutputHandle = "get_output_handle";
		public static readonly StringName GetChannelsPlaying = "get_channels_playing";
		public static readonly StringName GetCpuUsage = "get_cpu_usage";
		public static readonly StringName GetFileUsage = "get_file_usage";
		public static readonly StringName GetDefaultMixMatrix = "get_default_mix_matrix";
		public static readonly StringName GetSpeakerModeChannels = "get_speaker_mode_channels";
		public static readonly StringName CreateSoundFromFile = "create_sound_from_file";
		public static readonly StringName CreateSoundFromMemory = "create_sound_from_memory";
		public static readonly StringName CreateSoundFromRes = "create_sound_from_res";
		public static readonly StringName CreateStreamFromFile = "create_stream_from_file";
		public static readonly StringName CreateDsp = "create_dsp";
		public static readonly StringName CreateDspByType = "create_dsp_by_type";
		public static readonly StringName CreateChannelGroup = "create_channel_group";
		public static readonly StringName PlaySound = "play_sound";
		public static readonly StringName PlayDsp = "play_dsp";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName GetDspInfoByType = "get_dsp_info_by_type";
		public static readonly StringName GetMasterChannelGroup = "get_master_channel_group";
		public static readonly StringName GetRecordNumDrivers = "get_record_num_drivers";
		public static readonly StringName GetRecordDriverInfo = "get_record_driver_info";
		public static readonly StringName GetRecordPosition = "get_record_position";
		public static readonly StringName RecordStart = "record_start";
		public static readonly StringName RecordStop = "record_stop";
		public static readonly StringName IsRecording = "is_recording";
	}

	public class SignalName : Object.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodSystem";

	#region Enums

	public enum FmodInitFlags : long
	{
		Normal = 0L,
		StreamFromUpdate = 1L,
		MixFromUpdate = 2L,
		_3dRightHanded = 4L,
		ClipOutput = 8L,
		ChannelLowpass = 256L,
		ChannelDistanceFilter = 512L,
		ProfileEnable = 65536L,
		Vol0BecomesVirtual = 131072L,
		GeometryUseClosest = 262144L,
		PreferDolbyDownmix = 524288L,
		ThreadUnsafe = 1048576L,
		ProfileMeterAll = 2097152L,
		MemoryTracking = 4194304L,
	}

	public enum FmodOutputType : long
	{
		Autodetect = 0L,
		Unknown = 1L,
		NoSound = 2L,
		WavWriter = 3L,
		NoSoundNrt = 4L,
		WavWriterNrt = 5L,
		Wasapi = 6L,
		Asio = 7L,
		PulseAudio = 8L,
		Alsa = 9L,
		CoreAudio = 10L,
		AudioTrack = 11L,
		OpenSl = 12L,
		AudioOut = 13L,
		Audio3D = 14L,
		WebAudio = 15L,
		NnAudio = 16L,
		WinSonic = 17L,
		AAudio = 18L,
		AudioWorklet = 19L,
		Phase = 20L,
		OhAudio = 21L,
		Max = 22L,
		ForceInt = 65536L,
	}

	public enum FmodSpeakerMode : long
	{
		Default = 0L,
		Raw = 1L,
		Mono = 2L,
		Stereo = 3L,
		Quad = 4L,
		Surround = 5L,
		_5Point1 = 6L,
		_7Point1 = 7L,
		_7Point1Point4 = 8L,
		Max = 9L,
		ForceInt = 65536L,
	}

	public enum FmodMode : long
	{
		Default = 0L,
		LoopOff = 1L,
		LoopNormal = 2L,
		LoopBidi = 4L,
		_2d = 8L,
		_3d = 16L,
		CreateStream = 128L,
		CreateSample = 256L,
		CreateCompressedSample = 512L,
		OpenUser = 1024L,
		OpenMemory = 2048L,
		OpenMemoryPoint = 268435456L,
		OpenRaw = 4096L,
		OpenOnly = 8192L,
		AccurateTime = 16384L,
		MpegSearch = 32768L,
		NonBlocking = 65536L,
		Unique = 131072L,
		_3dHeadRelative = 262144L,
		_3dWorldRelative = 524288L,
		_3dInverseRolloff = 1048576L,
		_3dLinearRolloff = 2097152L,
		_3dLinearSquareRolloff = 4194304L,
		_3dInverseTaperedRolloff = 8388608L,
		_3dCustomRolloff = 67108864L,
		_3dIgnoreGeometry = 1073741824L,
		IgnoreTags = 33554432L,
		LowMem = 134217728L,
		VirtualPlayFromStart = -2147483648L,
	}

	public enum FmodTimeUnit : long
	{
		Ms = 1L,
		Pcm = 2L,
		PcmBytes = 4L,
		RawBytes = 8L,
		PcmFraction = 16L,
		ModOrder = 256L,
		ModRow = 512L,
		ModPattern = 1024L,
	}

	#endregion

	#region Methods

	public bool SystemIsValid()
	{
		return (bool)_object.Call(MethodName.SystemIsValid);
	}

	public bool SystemIsNull()
	{
		return (bool)_object.Call(MethodName.SystemIsNull);
	}

	public static FmodSystem CreateSystem(int @max_channels = 0, FmodSystem.FmodInitFlags @flags = (FmodSystem.FmodInitFlags)32)
	{
		return (FmodSystem)ClassDB.ClassCallStatic(NativeName, MethodName.CreateSystem, @max_channels, (int)@flags);
	}

	public void Init(int @max_channels = 0, FmodSystem.FmodInitFlags @flags = (FmodSystem.FmodInitFlags)32)
	{
		_object.Call(MethodName.Init, @max_channels, (int)@flags);
	}

	public void Close()
	{
		_object.Call(MethodName.Close);
	}

	public void Release()
	{
		_object.Call(MethodName.Release);
	}

	public void Update()
	{
		_object.Call(MethodName.Update);
	}

	public void MixerSuspend()
	{
		_object.Call(MethodName.MixerSuspend);
	}

	public void MixerResume()
	{
		_object.Call(MethodName.MixerResume);
	}

	public void SetOutput(FmodSystem.FmodOutputType @output_type)
	{
		_object.Call(MethodName.SetOutput, (int)@output_type);
	}

	public FmodSystem.FmodOutputType GetOutput()
	{
		return (FmodSystem.FmodOutputType)(int)_object.Call(MethodName.GetOutput);
	}

	public int GetNumDrivers()
	{
		return (int)_object.Call(MethodName.GetNumDrivers);
	}

	public Godot.Collections.Dictionary GetDriverInfo(int @id)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDriverInfo, @id);
	}

	public void SetDriver(int @driver)
	{
		_object.Call(MethodName.SetDriver, @driver);
	}

	public int GetDriver()
	{
		return (int)_object.Call(MethodName.GetDriver);
	}

	public void SetNetworkProxy(string @proxy)
	{
		_object.Call(MethodName.SetNetworkProxy, @proxy);
	}

	public string GetNetworkProxy()
	{
		return (string)_object.Call(MethodName.GetNetworkProxy);
	}

	public void SetNetworkTimeout(int @timeout)
	{
		_object.Call(MethodName.SetNetworkTimeout, @timeout);
	}

	public int GetNetworkTimeout()
	{
		return (int)_object.Call(MethodName.GetNetworkTimeout);
	}

	public Godot.Collections.Dictionary GetVersion()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetVersion);
	}

	public int GetOutputHandle()
	{
		return (int)_object.Call(MethodName.GetOutputHandle);
	}

	public Godot.Collections.Dictionary GetChannelsPlaying()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetChannelsPlaying);
	}

	public Godot.Collections.Dictionary GetCpuUsage()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetCpuUsage);
	}

	public Godot.Collections.Dictionary GetFileUsage()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetFileUsage);
	}

	public float[] GetDefaultMixMatrix(FmodSystem.FmodSpeakerMode @source_speaker_mode, FmodSystem.FmodSpeakerMode @target_speaker_mode, int @array_length, int @hop)
	{
		return (float[])_object.Call(MethodName.GetDefaultMixMatrix, (int)@source_speaker_mode, (int)@target_speaker_mode, @array_length, @hop);
	}

	public int GetSpeakerModeChannels(FmodSystem.FmodSpeakerMode @mode)
	{
		return (int)_object.Call(MethodName.GetSpeakerModeChannels, (int)@mode);
	}

	public FmodSound CreateSoundFromFile(string @path, int @mode = 0)
	{
		return (FmodSound)_object.Call(MethodName.CreateSoundFromFile, @path, @mode);
	}

	public FmodSound CreateSoundFromMemory(byte[] @data, int @mode = 0)
	{
		return (FmodSound)_object.Call(MethodName.CreateSoundFromMemory, @data, @mode);
	}

	public FmodSound CreateSoundFromRes(string @path, int @mode = 0)
	{
		return (FmodSound)_object.Call(MethodName.CreateSoundFromRes, @path, @mode);
	}

	public FmodSound CreateStreamFromFile(string @path, int @mode = 0)
	{
		return (FmodSound)_object.Call(MethodName.CreateStreamFromFile, @path, @mode);
	}

	public FmodDsp CreateDsp(string @name)
	{
		return (FmodDsp)_object.Call(MethodName.CreateDsp, @name);
	}

	public FmodDsp CreateDspByType(int @type)
	{
		return (FmodDsp)_object.Call(MethodName.CreateDspByType, @type);
	}

	public FmodChannelGroup CreateChannelGroup(string @name)
	{
		return (FmodChannelGroup)_object.Call(MethodName.CreateChannelGroup, @name);
	}

	public FmodChannel PlaySound(FmodSound @sound, FmodChannelGroup @channel_group, bool @paused = false)
	{
		return (FmodChannel)_object.Call(MethodName.PlaySound, @sound, @channel_group, @paused);
	}

	public FmodChannel PlayDsp(FmodDsp @dsp, FmodChannelGroup @channel_group, bool @paused = false)
	{
		return (FmodChannel)_object.Call(MethodName.PlayDsp, @dsp, @channel_group, @paused);
	}

	public FmodChannel GetChannel(int @id)
	{
		return (FmodChannel)_object.Call(MethodName.GetChannel, @id);
	}

	public Godot.Collections.Dictionary GetDspInfoByType(int @type)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDspInfoByType, @type);
	}

	public FmodChannelGroup GetMasterChannelGroup()
	{
		return (FmodChannelGroup)_object.Call(MethodName.GetMasterChannelGroup);
	}

	public Godot.Collections.Dictionary GetRecordNumDrivers()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRecordNumDrivers);
	}

	public Godot.Collections.Dictionary GetRecordDriverInfo(int @id)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRecordDriverInfo, @id);
	}

	public int GetRecordPosition(int @id)
	{
		return (int)_object.Call(MethodName.GetRecordPosition, @id);
	}

	public void RecordStart(int @id, FmodSound @sound, bool @loop)
	{
		_object.Call(MethodName.RecordStart, @id, @sound, @loop);
	}

	public void RecordStop(int @id)
	{
		_object.Call(MethodName.RecordStop, @id);
	}

	public bool IsRecording(int @id)
	{
		return (bool)_object.Call(MethodName.IsRecording, @id);
	}

	#endregion

	#region Inherited Methods

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
