// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectCapture : FmodAudioEffect
{
	public FmodAudioEffectCapture() : base(NativeName)
	{
	}
	protected FmodAudioEffectCapture(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectCapture(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectCapture([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectCapture self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectCapture self) => self?._object;
	public static explicit operator FmodAudioEffectCapture(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName BufferLength = "buffer_length";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetBufferLength = "set_buffer_length";
		public static readonly StringName GetBufferLength = "get_buffer_length";
		public static readonly StringName CanGetBuffer = "can_get_buffer";
		public static readonly StringName ClearBuffer = "clear_buffer";
		public static readonly StringName GetBuffer = "get_buffer";
		public static readonly StringName GetDiscardedFrames = "get_discarded_frames";
		public static readonly StringName GetFramesAvailable = "get_frames_available";
		public static readonly StringName GetPushedFrames = "get_pushed_frames";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectCapture";

	#region Properties

	public float BufferLength
	{
		get => (float)_object.Get(PropertyName.BufferLength);
		set => _object.Set(PropertyName.BufferLength, value);
	}

	#endregion

	#region Methods

	public void SetBufferLength(float @buffer_length)
	{
		_object.Call(MethodName.SetBufferLength, @buffer_length);
	}

	public float GetBufferLength()
	{
		return (float)_object.Call(MethodName.GetBufferLength);
	}

	public bool CanGetBuffer(int @frames)
	{
		return (bool)_object.Call(MethodName.CanGetBuffer, @frames);
	}

	public void ClearBuffer()
	{
		_object.Call(MethodName.ClearBuffer);
	}

	public Godot.Vector2[] GetBuffer(int @frames)
	{
		return (Godot.Vector2[])_object.Call(MethodName.GetBuffer, @frames);
	}

	public int GetDiscardedFrames()
	{
		return (int)_object.Call(MethodName.GetDiscardedFrames);
	}

	public int GetFramesAvailable()
	{
		return (int)_object.Call(MethodName.GetFramesAvailable);
	}

	public int GetPushedFrames()
	{
		return (int)_object.Call(MethodName.GetPushedFrames);
	}

	#endregion
}
