// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodChannelGroup : FmodChannelControl
{
	public FmodChannelGroup() : base(NativeName)
	{
	}
	protected FmodChannelGroup(StringName @class) : base(@class)
	{
	}
	protected FmodChannelGroup(Variant variant) : base(variant)
	{
	}
	protected FmodChannelGroup([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(FmodChannelGroup self) => self?._object;
	public static implicit operator Variant(FmodChannelGroup self) => self?._object;
	public static explicit operator FmodChannelGroup(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodChannelControl.PropertyName
	{

	}

	public new class MethodName : FmodChannelControl.MethodName
	{
		public static readonly StringName ChannelGroupIsValid = "channel_group_is_valid";
		public static readonly StringName ChannelGroupIsNull = "channel_group_is_null";
		public static readonly StringName GetNumChannels = "get_num_channels";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName AddGroup = "add_group";
		public static readonly StringName GetNumGroups = "get_num_groups";
		public static readonly StringName GetGroup = "get_group";
		public static readonly StringName GetParentGroup = "get_parent_group";
		public static readonly StringName GetName = "get_name";
		public static readonly StringName Release = "release";
	}

	public new class SignalName : FmodChannelControl.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodChannelGroup";

	#region Methods

	public bool ChannelGroupIsValid()
	{
		return (bool)_object.Call(MethodName.ChannelGroupIsValid);
	}

	public bool ChannelGroupIsNull()
	{
		return (bool)_object.Call(MethodName.ChannelGroupIsNull);
	}

	public int GetNumChannels()
	{
		return (int)_object.Call(MethodName.GetNumChannels);
	}

	public FmodChannel GetChannel(int @index)
	{
		return (FmodChannel)_object.Call(MethodName.GetChannel, @index);
	}

	public void AddGroup(FmodChannelGroup @child_group, bool @propagatedspclock = true)
	{
		_object.Call(MethodName.AddGroup, @child_group, @propagatedspclock);
	}

	public int GetNumGroups()
	{
		return (int)_object.Call(MethodName.GetNumGroups);
	}

	public FmodChannelGroup GetGroup(int @index)
	{
		return (FmodChannelGroup)_object.Call(MethodName.GetGroup, @index);
	}

	public FmodChannelGroup GetParentGroup()
	{
		return (FmodChannelGroup)_object.Call(MethodName.GetParentGroup);
	}

	public string GetName()
	{
		return (string)_object.Call(MethodName.GetName);
	}

	public void Release()
	{
		_object.Call(MethodName.Release);
	}

	#endregion
}
