// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectPitchShift : FmodAudioEffect
{
	public FmodAudioEffectPitchShift() : base(NativeName)
	{
	}
	protected FmodAudioEffectPitchShift(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectPitchShift(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectPitchShift([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectPitchShift self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectPitchShift self) => self?._object;
	public static explicit operator FmodAudioEffectPitchShift(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName PitchScale = "pitch_scale";
		public static readonly StringName FftSize = "fft_size";
		public static readonly StringName Oversampling = "oversampling";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetPitchScale = "set_pitch_scale";
		public static readonly StringName GetPitchScale = "get_pitch_scale";
		public static readonly StringName SetFftSize = "set_fft_size";
		public static readonly StringName GetFftSize = "get_fft_size";
		public static readonly StringName SetOversampling = "set_oversampling";
		public static readonly StringName GetOversampling = "get_oversampling";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectPitchShift";

	#region Enums

	public enum FFTSizeEnum : long
	{
		_256 = 0L,
		_512 = 1L,
		_1024 = 2L,
		_2048 = 3L,
		_4096 = 4L,
		Max = 5L,
	}

	#endregion

	#region Properties

	public float PitchScale
	{
		get => (float)_object.Get(PropertyName.PitchScale);
		set => _object.Set(PropertyName.PitchScale, value);
	}

	public FmodAudioEffectPitchShift.FFTSizeEnum FftSize
	{
		get => (FmodAudioEffectPitchShift.FFTSizeEnum)(int)_object.Get(PropertyName.FftSize);
		set => _object.Set(PropertyName.FftSize, (int)value);
	}

	public int Oversampling
	{
		get => (int)_object.Get(PropertyName.Oversampling);
		set => _object.Set(PropertyName.Oversampling, value);
	}

	#endregion

	#region Methods

	public void SetPitchScale(float @pitch_scale)
	{
		_object.Call(MethodName.SetPitchScale, @pitch_scale);
	}

	public float GetPitchScale()
	{
		return (float)_object.Call(MethodName.GetPitchScale);
	}

	public void SetFftSize(FmodAudioEffectPitchShift.FFTSizeEnum @fft_size)
	{
		_object.Call(MethodName.SetFftSize, (int)@fft_size);
	}

	public FmodAudioEffectPitchShift.FFTSizeEnum GetFftSize()
	{
		return (FmodAudioEffectPitchShift.FFTSizeEnum)(int)_object.Call(MethodName.GetFftSize);
	}

	public void SetOversampling(int @oversampling)
	{
		_object.Call(MethodName.SetOversampling, @oversampling);
	}

	public int GetOversampling()
	{
		return (int)_object.Call(MethodName.GetOversampling);
	}

	#endregion
}
