// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodChannel : FmodChannelControl
{
	public FmodChannel() : base(NativeName)
	{
	}
	protected FmodChannel(StringName @class) : base(@class)
	{
	}
	protected FmodChannel(Variant variant) : base(variant)
	{
	}
	protected FmodChannel([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(FmodChannel self) => self?._object;
	public static implicit operator Variant(FmodChannel self) => self?._object;
	public static explicit operator FmodChannel(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodChannelControl.PropertyName
	{
		public static readonly StringName Frequency = "frequency";
		public static readonly StringName Priority = "priority";
		public static readonly StringName ChannelGroup = "channel_group";
		public static readonly StringName LoopCount = "loop_count";
	}

	public new class MethodName : FmodChannelControl.MethodName
	{
		public static readonly StringName ChannelIsValid = "channel_is_valid";
		public static readonly StringName ChannelIsNull = "channel_is_null";
		public static readonly StringName SetFrequency = "set_frequency";
		public static readonly StringName GetFrequency = "get_frequency";
		public static readonly StringName SetPriority = "set_priority";
		public static readonly StringName GetPriority = "get_priority";
		public static readonly StringName SetPosition = "set_position";
		public static readonly StringName GetPosition = "get_position";
		public static readonly StringName SetChannelGroup = "set_channel_group";
		public static readonly StringName GetChannelGroup = "get_channel_group";
		public static readonly StringName SetLoopCount = "set_loop_count";
		public static readonly StringName GetLoopCount = "get_loop_count";
		public static readonly StringName SetLoopPoints = "set_loop_points";
		public static readonly StringName GetLoopPoints = "get_loop_points";
		public static readonly StringName IsVirtual = "is_virtual";
		public static readonly StringName GetCurrentSound = "get_current_sound";
		public static readonly StringName GetIndex = "get_index";
	}

	public new class SignalName : FmodChannelControl.SignalName
	{
		public static readonly StringName Ended = "ended";
		public static readonly StringName Virtualvoice = "virtualvoice";
		public static readonly StringName Syncpoint = "syncpoint";
		public static readonly StringName Occlusion = "occlusion";
	}

	private static readonly StringName NativeName = "FmodChannel";

	#region Properties

	public float Frequency
	{
		get => (float)_object.Get(PropertyName.Frequency);
		set => _object.Set(PropertyName.Frequency, value);
	}

	public int Priority
	{
		get => (int)_object.Get(PropertyName.Priority);
		set => _object.Set(PropertyName.Priority, value);
	}

	public GodotObject ChannelGroup
	{
		get => (GodotObject)_object.Get(PropertyName.ChannelGroup);
		set => _object.Set(PropertyName.ChannelGroup, value);
	}

	public int LoopCount
	{
		get => (int)_object.Get(PropertyName.LoopCount);
		set => _object.Set(PropertyName.LoopCount, value);
	}

	#endregion

	#region Methods

	public bool ChannelIsValid()
	{
		return (bool)_object.Call(MethodName.ChannelIsValid);
	}

	public bool ChannelIsNull()
	{
		return (bool)_object.Call(MethodName.ChannelIsNull);
	}

	public void SetFrequency(float @frequency)
	{
		_object.Call(MethodName.SetFrequency, @frequency);
	}

	public float GetFrequency()
	{
		return (float)_object.Call(MethodName.GetFrequency);
	}

	public void SetPriority(int @priority)
	{
		_object.Call(MethodName.SetPriority, @priority);
	}

	public int GetPriority()
	{
		return (int)_object.Call(MethodName.GetPriority);
	}

	public void SetPosition(int @position, FmodSystem.FmodTimeUnit @timeunit = (FmodSystem.FmodTimeUnit)1)
	{
		_object.Call(MethodName.SetPosition, @position, (int)@timeunit);
	}

	public int GetPosition(FmodSystem.FmodTimeUnit @timeunit = (FmodSystem.FmodTimeUnit)1)
	{
		return (int)_object.Call(MethodName.GetPosition, (int)@timeunit);
	}

	public void SetChannelGroup(FmodChannelGroup @channel_group)
	{
		_object.Call(MethodName.SetChannelGroup, @channel_group);
	}

	public FmodChannelGroup GetChannelGroup()
	{
		return (FmodChannelGroup)_object.Call(MethodName.GetChannelGroup);
	}

	public void SetLoopCount(int @loop_count)
	{
		_object.Call(MethodName.SetLoopCount, @loop_count);
	}

	public int GetLoopCount()
	{
		return (int)_object.Call(MethodName.GetLoopCount);
	}

	public void SetLoopPoints(int @start, int @end, FmodSystem.FmodTimeUnit @timeunit = (FmodSystem.FmodTimeUnit)1)
	{
		_object.Call(MethodName.SetLoopPoints, @start, @end, (int)@timeunit);
	}

	public Godot.Collections.Dictionary GetLoopPoints(FmodSystem.FmodTimeUnit @_unnamed_arg0)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetLoopPoints, (int)@_unnamed_arg0);
	}

	public bool IsVirtual()
	{
		return (bool)_object.Call(MethodName.IsVirtual);
	}

	public FmodSound GetCurrentSound()
	{
		return (FmodSound)_object.Call(MethodName.GetCurrentSound);
	}

	public int GetIndex()
	{
		return (int)_object.Call(MethodName.GetIndex);
	}

	#endregion

	#region Signals

	public event Action Ended
	{
		add
		{
			Connect(SignalName.Ended, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Ended, Callable.From(value));
		}
	}

	public event Action<bool> Virtualvoice
	{
		add
		{
			Connect(SignalName.Virtualvoice, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Virtualvoice, Callable.From(value));
		}
	}

	public event Action<int> Syncpoint
	{
		add
		{
			Connect(SignalName.Syncpoint, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Syncpoint, Callable.From(value));
		}
	}

	public event Action<float, float> Occlusion
	{
		add
		{
			Connect(SignalName.Occlusion, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Occlusion, Callable.From(value));
		}
	}

	#endregion
}
