// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectAmplify : FmodAudioEffect
{
	public FmodAudioEffectAmplify() : base(NativeName)
	{
	}
	protected FmodAudioEffectAmplify(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectAmplify(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectAmplify([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectAmplify self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectAmplify self) => self?._object;
	public static explicit operator FmodAudioEffectAmplify(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName VolumeDb = "volume_db";
		public static readonly StringName VolumeLinear = "volume_linear";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetVolumeDb = "set_volume_db";
		public static readonly StringName GetVolumeDb = "get_volume_db";
		public static readonly StringName SetVolumeLinear = "set_volume_linear";
		public static readonly StringName GetVolumeLinear = "get_volume_linear";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectAmplify";

	#region Properties

	public float VolumeDb
	{
		get => (float)_object.Get(PropertyName.VolumeDb);
		set => _object.Set(PropertyName.VolumeDb, value);
	}

	public float VolumeLinear
	{
		get => (float)_object.Get(PropertyName.VolumeLinear);
		set => _object.Set(PropertyName.VolumeLinear, value);
	}

	#endregion

	#region Methods

	public void SetVolumeDb(float @volume_db)
	{
		_object.Call(MethodName.SetVolumeDb, @volume_db);
	}

	public float GetVolumeDb()
	{
		return (float)_object.Call(MethodName.GetVolumeDb);
	}

	public void SetVolumeLinear(float @volume_linear)
	{
		_object.Call(MethodName.SetVolumeLinear, @volume_linear);
	}

	public float GetVolumeLinear()
	{
		return (float)_object.Call(MethodName.GetVolumeLinear);
	}

	#endregion
}
