// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectPanner : FmodAudioEffect
{
	public FmodAudioEffectPanner() : base(NativeName)
	{
	}
	protected FmodAudioEffectPanner(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectPanner(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectPanner([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectPanner self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectPanner self) => self?._object;
	public static explicit operator FmodAudioEffectPanner(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Pan = "pan";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetPan = "set_pan";
		public static readonly StringName GetPan = "get_pan";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectPanner";

	#region Properties

	public float Pan
	{
		get => (float)_object.Get(PropertyName.Pan);
		set => _object.Set(PropertyName.Pan, value);
	}

	#endregion

	#region Methods

	public void SetPan(float @pan)
	{
		_object.Call(MethodName.SetPan, @pan);
	}

	public float GetPan()
	{
		return (float)_object.Call(MethodName.GetPan);
	}

	#endregion
}
