// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectHardLimiter : FmodAudioEffect
{
	public FmodAudioEffectHardLimiter() : base(NativeName)
	{
	}
	protected FmodAudioEffectHardLimiter(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectHardLimiter(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectHardLimiter([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectHardLimiter self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectHardLimiter self) => self?._object;
	public static explicit operator FmodAudioEffectHardLimiter(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName CeilingDb = "ceiling_db";
		public static readonly StringName PreGainDb = "pre_gain_db";
		public static readonly StringName Release = "release";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetCeilingDb = "set_ceiling_db";
		public static readonly StringName GetCeilingDb = "get_ceiling_db";
		public static readonly StringName SetPreGainDb = "set_pre_gain_db";
		public static readonly StringName GetPreGainDb = "get_pre_gain_db";
		public static readonly StringName SetRelease = "set_release";
		public static readonly StringName GetRelease = "get_release";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectHardLimiter";

	#region Properties

	public float CeilingDb
	{
		get => (float)_object.Get(PropertyName.CeilingDb);
		set => _object.Set(PropertyName.CeilingDb, value);
	}

	public float PreGainDb
	{
		get => (float)_object.Get(PropertyName.PreGainDb);
		set => _object.Set(PropertyName.PreGainDb, value);
	}

	public float Release
	{
		get => (float)_object.Get(PropertyName.Release);
		set => _object.Set(PropertyName.Release, value);
	}

	#endregion

	#region Methods

	public void SetCeilingDb(float @ceiling_db)
	{
		_object.Call(MethodName.SetCeilingDb, @ceiling_db);
	}

	public float GetCeilingDb()
	{
		return (float)_object.Call(MethodName.GetCeilingDb);
	}

	public void SetPreGainDb(float @pre_gain_db)
	{
		_object.Call(MethodName.SetPreGainDb, @pre_gain_db);
	}

	public float GetPreGainDb()
	{
		return (float)_object.Call(MethodName.GetPreGainDb);
	}

	public void SetRelease(float @release)
	{
		_object.Call(MethodName.SetRelease, @release);
	}

	public float GetRelease()
	{
		return (float)_object.Call(MethodName.GetRelease);
	}

	#endregion
}
