// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodDSP
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public FmodDSP() : this(NativeName)
	{
	}
	protected FmodDSP(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected FmodDSP(Variant variant) : this((RefCounted) variant)
	{
	}
	protected FmodDSP([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(FmodDSP self) => self?._object;
	public static implicit operator Variant(FmodDSP self) => self?._object;
	public static explicit operator FmodDSP(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Active = "active";
		public static readonly StringName Bypass = "bypass";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName AddInput = "add_input";
		public static readonly StringName GetInput = "get_input";
		public static readonly StringName GetOutput = "get_output";
		public static readonly StringName GetNumInputs = "get_num_inputs";
		public static readonly StringName GetNumOutputs = "get_num_outputs";
		public static readonly StringName DisconnectAll = "disconnect_all";
		public static readonly StringName DisconnectFrom = "disconnect_from";
		public static readonly StringName SetChannelFormat = "set_channel_format";
		public static readonly StringName GetChannelFormat = "get_channel_format";
		public static readonly StringName GetOutputChannelFormat = "get_output_channel_format";
		public static readonly StringName GetMeteringInfo = "get_metering_info";
		public static readonly StringName SetMeteringEnabled = "set_metering_enabled";
		public static readonly StringName GetMeteringEnabled = "get_metering_enabled";
		public static readonly StringName GetDataParameterIndex = "get_data_parameter_index";
		public static readonly StringName GetNumParameters = "get_num_parameters";
		public static readonly StringName SetParameterBool = "set_parameter_bool";
		public static readonly StringName GetParameterBool = "get_parameter_bool";
		public static readonly StringName SetParameterData = "set_parameter_data";
		public static readonly StringName GetParameterData = "get_parameter_data";
		public static readonly StringName SetParameterFloat = "set_parameter_float";
		public static readonly StringName GetParameterFloat = "get_parameter_float";
		public static readonly StringName SetParameterInt = "set_parameter_int";
		public static readonly StringName GetParameterInt = "get_parameter_int";
		public static readonly StringName GetParameterInfo = "get_parameter_info";
		public static readonly StringName SetActive = "set_active";
		public static readonly StringName GetActive = "get_active";
		public static readonly StringName SetBypass = "set_bypass";
		public static readonly StringName GetBypass = "get_bypass";
		public static readonly StringName SetWetDryMix = "set_wet_dry_mix";
		public static readonly StringName GetWetDryMix = "get_wet_dry_mix";
		public static readonly StringName GetIdle = "get_idle";
		public static readonly StringName Reset = "reset";
		public static readonly StringName Release = "release";
		public static readonly StringName GetType = "get_type";
		public static readonly StringName GetInfo = "get_info";
		public static readonly StringName GetCpuUsage = "get_cpu_usage";
		public static readonly StringName GetSystemObject = "get_system_object";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodDSP";

	#region Enums

	public enum FmodDSPType : long
	{
		Unknown = 0L,
		Mixer = 1L,
		Oscillator = 2L,
		Lowpass = 3L,
		ItLowpass = 4L,
		Highpass = 5L,
		Echo = 6L,
		Fader = 7L,
		Flange = 8L,
		Distortion = 9L,
		Normalize = 10L,
		Limiter = 11L,
		ParamEq = 12L,
		PitchShift = 13L,
		Chorus = 14L,
		ItEcho = 15L,
		Compressor = 16L,
		SfxReverb = 17L,
		LowpassSimple = 18L,
		Delay = 19L,
		Tremolo = 20L,
		Send = 21L,
		Return = 22L,
		HighpassSimple = 23L,
		Pan = 24L,
		ThreeEq = 25L,
		FFT = 26L,
		LoudnessMeter = 27L,
		ConvolutionReverb = 28L,
		ChannelMix = 29L,
		Transceiver = 30L,
		ObjectPan = 31L,
		MultibandEq = 32L,
		MultibandDynamics = 33L,
		Max = 34L,
		ForceInt = 65536L,
	}

	public enum FmodDSPParameterDataType : long
	{
		User = 0L,
		OverallGain = -1L,
		_3dAttributes = -2L,
		Sidechain = -3L,
		FFT = -4L,
		_3dAttributesMulti = -5L,
		AttenuationRange = -6L,
		DynamicResponse = -7L,
		FiniteLength = -8L,
	}

	#endregion

	#region Properties

	public bool Active
	{
		get => (bool)_object.Get(PropertyName.Active);
		set => _object.Set(PropertyName.Active, value);
	}

	public bool Bypass
	{
		get => (bool)_object.Get(PropertyName.Bypass);
		set => _object.Set(PropertyName.Bypass, value);
	}

	#endregion

	#region Methods

	public FmodDspConnection AddInput(FmodDsp @target_dsp, int @type = 0)
	{
		return (FmodDspConnection)_object.Call(MethodName.AddInput, @target_dsp, @type);
	}

	public Godot.Collections.Dictionary GetInput(int @index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetInput, @index);
	}

	public Godot.Collections.Dictionary GetOutput(int @index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetOutput, @index);
	}

	public int GetNumInputs()
	{
		return (int)_object.Call(MethodName.GetNumInputs);
	}

	public int GetNumOutputs()
	{
		return (int)_object.Call(MethodName.GetNumOutputs);
	}

	public void DisconnectAll(bool @inputs, bool @outputs)
	{
		_object.Call(MethodName.DisconnectAll, @inputs, @outputs);
	}

	public void DisconnectFrom(FmodDsp @target, FmodDspConnection @connection = default)
	{
		_object.Call(MethodName.DisconnectFrom, @target, @connection);
	}

	public void SetChannelFormat(int @numchannels, FmodSystem.FmodSpeakerMode @speakermode)
	{
		_object.Call(MethodName.SetChannelFormat, @numchannels, (int)@speakermode);
	}

	public Godot.Collections.Dictionary GetChannelFormat()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetChannelFormat);
	}

	public Godot.Collections.Dictionary GetOutputChannelFormat(int @inchannels, FmodSystem.FmodSpeakerMode @inspeakermode)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetOutputChannelFormat, @inchannels, (int)@inspeakermode);
	}

	public Godot.Collections.Dictionary GetMeteringInfo()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMeteringInfo);
	}

	public void SetMeteringEnabled(bool @input_enabled, bool @output_enabled)
	{
		_object.Call(MethodName.SetMeteringEnabled, @input_enabled, @output_enabled);
	}

	public Godot.Collections.Dictionary GetMeteringEnabled()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMeteringEnabled);
	}

	public int GetDataParameterIndex(FmodDSP.FmodDSPParameterDataType @data_type)
	{
		return (int)_object.Call(MethodName.GetDataParameterIndex, (int)@data_type);
	}

	public int GetNumParameters()
	{
		return (int)_object.Call(MethodName.GetNumParameters);
	}

	public void SetParameterBool(int @index, bool @value)
	{
		_object.Call(MethodName.SetParameterBool, @index, @value);
	}

	public bool GetParameterBool(int @index)
	{
		return (bool)_object.Call(MethodName.GetParameterBool, @index);
	}

	public void SetParameterData(int @index, byte[] @data)
	{
		_object.Call(MethodName.SetParameterData, @index, @data);
	}

	public byte[] GetParameterData(int @index)
	{
		return (byte[])_object.Call(MethodName.GetParameterData, @index);
	}

	public void SetParameterFloat(int @index, float @value)
	{
		_object.Call(MethodName.SetParameterFloat, @index, @value);
	}

	public float GetParameterFloat(int @index)
	{
		return (float)_object.Call(MethodName.GetParameterFloat, @index);
	}

	public void SetParameterInt(int @index, int @value)
	{
		_object.Call(MethodName.SetParameterInt, @index, @value);
	}

	public int GetParameterInt(int @index)
	{
		return (int)_object.Call(MethodName.GetParameterInt, @index);
	}

	public Godot.Collections.Dictionary GetParameterInfo(int @index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetParameterInfo, @index);
	}

	public void SetActive(bool @active)
	{
		_object.Call(MethodName.SetActive, @active);
	}

	public bool GetActive()
	{
		return (bool)_object.Call(MethodName.GetActive);
	}

	public void SetBypass(bool @bypass)
	{
		_object.Call(MethodName.SetBypass, @bypass);
	}

	public bool GetBypass()
	{
		return (bool)_object.Call(MethodName.GetBypass);
	}

	public void SetWetDryMix(float @prewet, float @postwet, float @dry)
	{
		_object.Call(MethodName.SetWetDryMix, @prewet, @postwet, @dry);
	}

	public Godot.Collections.Dictionary GetWetDryMix()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetWetDryMix);
	}

	public bool GetIdle()
	{
		return (bool)_object.Call(MethodName.GetIdle);
	}

	public void Reset()
	{
		_object.Call(MethodName.Reset);
	}

	public void Release()
	{
		_object.Call(MethodName.Release);
	}

	public FmodDSP.FmodDSPType GetType()
	{
		return (FmodDSP.FmodDSPType)(int)_object.Call(MethodName.GetType);
	}

	public Godot.Collections.Dictionary GetInfo()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetInfo);
	}

	public Godot.Collections.Dictionary GetCpuUsage()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetCpuUsage);
	}

	public FmodSystem GetSystemObject()
	{
		return (FmodSystem)_object.Call(MethodName.GetSystemObject);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
