// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectDistortion : FmodAudioEffect
{
	public FmodAudioEffectDistortion() : base(NativeName)
	{
	}
	protected FmodAudioEffectDistortion(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectDistortion(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectDistortion([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectDistortion self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectDistortion self) => self?._object;
	public static explicit operator FmodAudioEffectDistortion(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Mode = "mode";
		public static readonly StringName PreGain = "pre_gain";
		public static readonly StringName Drive = "drive";
		public static readonly StringName PostGain = "post_gain";
		public static readonly StringName KeepHfHz = "keep_hf_hz";
		public static readonly StringName Oversample = "oversample";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetMode = "set_mode";
		public static readonly StringName GetMode = "get_mode";
		public static readonly StringName SetPreGain = "set_pre_gain";
		public static readonly StringName GetPreGain = "get_pre_gain";
		public static readonly StringName SetDrive = "set_drive";
		public static readonly StringName GetDrive = "get_drive";
		public static readonly StringName SetPostGain = "set_post_gain";
		public static readonly StringName GetPostGain = "get_post_gain";
		public static readonly StringName SetKeepHfHz = "set_keep_hf_hz";
		public static readonly StringName GetKeepHfHz = "get_keep_hf_hz";
		public static readonly StringName SetOversample = "set_oversample";
		public static readonly StringName GetOversample = "get_oversample";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectDistortion";

	#region Enums

	public enum ModeEnum : long
	{
		Clip = 0L,
		Atan = 1L,
		Lofi = 2L,
		Overdrive = 3L,
		Waveshape = 4L,
		Bitcrush = 5L,
	}

	#endregion

	#region Properties

	public FmodAudioEffectDistortion.ModeEnum Mode
	{
		get => (FmodAudioEffectDistortion.ModeEnum)(int)_object.Get(PropertyName.Mode);
		set => _object.Set(PropertyName.Mode, (int)value);
	}

	public float PreGain
	{
		get => (float)_object.Get(PropertyName.PreGain);
		set => _object.Set(PropertyName.PreGain, value);
	}

	public float Drive
	{
		get => (float)_object.Get(PropertyName.Drive);
		set => _object.Set(PropertyName.Drive, value);
	}

	public float PostGain
	{
		get => (float)_object.Get(PropertyName.PostGain);
		set => _object.Set(PropertyName.PostGain, value);
	}

	public float KeepHfHz
	{
		get => (float)_object.Get(PropertyName.KeepHfHz);
		set => _object.Set(PropertyName.KeepHfHz, value);
	}

	public int Oversample
	{
		get => (int)_object.Get(PropertyName.Oversample);
		set => _object.Set(PropertyName.Oversample, value);
	}

	#endregion

	#region Methods

	public void SetMode(FmodAudioEffectDistortion.ModeEnum @mode)
	{
		_object.Call(MethodName.SetMode, (int)@mode);
	}

	public FmodAudioEffectDistortion.ModeEnum GetMode()
	{
		return (FmodAudioEffectDistortion.ModeEnum)(int)_object.Call(MethodName.GetMode);
	}

	public void SetPreGain(float @gain)
	{
		_object.Call(MethodName.SetPreGain, @gain);
	}

	public float GetPreGain()
	{
		return (float)_object.Call(MethodName.GetPreGain);
	}

	public void SetDrive(float @drive)
	{
		_object.Call(MethodName.SetDrive, @drive);
	}

	public float GetDrive()
	{
		return (float)_object.Call(MethodName.GetDrive);
	}

	public void SetPostGain(float @gain)
	{
		_object.Call(MethodName.SetPostGain, @gain);
	}

	public float GetPostGain()
	{
		return (float)_object.Call(MethodName.GetPostGain);
	}

	public void SetKeepHfHz(float @hz)
	{
		_object.Call(MethodName.SetKeepHfHz, @hz);
	}

	public float GetKeepHfHz()
	{
		return (float)_object.Call(MethodName.GetKeepHfHz);
	}

	public void SetOversample(int @oversample)
	{
		_object.Call(MethodName.SetOversample, @oversample);
	}

	public int GetOversample()
	{
		return (int)_object.Call(MethodName.GetOversample);
	}

	#endregion
}
