// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectFilter : FmodAudioEffect
{
	public FmodAudioEffectFilter() : base(NativeName)
	{
	}
	protected FmodAudioEffectFilter(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectFilter(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectFilter([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectFilter self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectFilter self) => self?._object;
	public static explicit operator FmodAudioEffectFilter(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName CutoffHz = "cutoff_hz";
		public static readonly StringName Db = "db";
		public static readonly StringName Gain = "gain";
		public static readonly StringName Resonance = "resonance";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetCutoffHz = "set_cutoff_hz";
		public static readonly StringName GetCutoffHz = "get_cutoff_hz";
		public static readonly StringName SetDb = "set_db";
		public static readonly StringName GetDb = "get_db";
		public static readonly StringName SetGain = "set_gain";
		public static readonly StringName GetGain = "get_gain";
		public static readonly StringName SetResonance = "set_resonance";
		public static readonly StringName GetResonance = "get_resonance";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectFilter";

	#region Enums

	public enum FilterDB : long
	{
		_6dB = 0L,
		_12dB = 1L,
		_18dB = 2L,
		_24dB = 3L,
	}

	#endregion

	#region Properties

	public float CutoffHz
	{
		get => (float)_object.Get(PropertyName.CutoffHz);
		set => _object.Set(PropertyName.CutoffHz, value);
	}

	public FmodAudioEffectFilter.FilterDB Db
	{
		get => (FmodAudioEffectFilter.FilterDB)(int)_object.Get(PropertyName.Db);
		set => _object.Set(PropertyName.Db, (int)value);
	}

	public float Gain
	{
		get => (float)_object.Get(PropertyName.Gain);
		set => _object.Set(PropertyName.Gain, value);
	}

	public float Resonance
	{
		get => (float)_object.Get(PropertyName.Resonance);
		set => _object.Set(PropertyName.Resonance, value);
	}

	#endregion

	#region Methods

	public void SetCutoffHz(float @cutoff_hz)
	{
		_object.Call(MethodName.SetCutoffHz, @cutoff_hz);
	}

	public float GetCutoffHz()
	{
		return (float)_object.Call(MethodName.GetCutoffHz);
	}

	public void SetDb(FmodAudioEffectFilter.FilterDB @db)
	{
		_object.Call(MethodName.SetDb, (int)@db);
	}

	public FmodAudioEffectFilter.FilterDB GetDb()
	{
		return (FmodAudioEffectFilter.FilterDB)(int)_object.Call(MethodName.GetDb);
	}

	public void SetGain(float @gain)
	{
		_object.Call(MethodName.SetGain, @gain);
	}

	public float GetGain()
	{
		return (float)_object.Call(MethodName.GetGain);
	}

	public void SetResonance(float @resonance)
	{
		_object.Call(MethodName.SetResonance, @resonance);
	}

	public float GetResonance()
	{
		return (float)_object.Call(MethodName.GetResonance);
	}

	#endregion
}
