// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectEQ10 : FmodAudioEffectEQ
{
	public FmodAudioEffectEQ10() : base(NativeName)
	{
	}
	protected FmodAudioEffectEQ10(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectEQ10(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectEQ10([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectEQ10 self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectEQ10 self) => self?._object;
	public static explicit operator FmodAudioEffectEQ10(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffectEQ.PropertyName
	{

	}

	public new class MethodName : FmodAudioEffectEQ.MethodName
	{

	}

	public new class SignalName : FmodAudioEffectEQ.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectEQ10";
}
