// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectReverb : FmodAudioEffect
{
	public FmodAudioEffectReverb() : base(NativeName)
	{
	}
	protected FmodAudioEffectReverb(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectReverb(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectReverb([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectReverb self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectReverb self) => self?._object;
	public static explicit operator FmodAudioEffectReverb(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName Damping = "damping";
		public static readonly StringName Dry = "dry";
		public static readonly StringName Hipass = "hipass";
		public static readonly StringName PredelayFeedback = "predelay_feedback";
		public static readonly StringName PredelayMsec = "predelay_msec";
		public static readonly StringName RoomSize = "room_size";
		public static readonly StringName Spread = "spread";
		public static readonly StringName Wet = "wet";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetDamping = "set_damping";
		public static readonly StringName GetDamping = "get_damping";
		public static readonly StringName SetDry = "set_dry";
		public static readonly StringName GetDry = "get_dry";
		public static readonly StringName SetHpf = "set_hpf";
		public static readonly StringName GetHpf = "get_hpf";
		public static readonly StringName SetPredelayFeedback = "set_predelay_feedback";
		public static readonly StringName GetPredelayFeedback = "get_predelay_feedback";
		public static readonly StringName SetPredelayMsec = "set_predelay_msec";
		public static readonly StringName GetPredelayMsec = "get_predelay_msec";
		public static readonly StringName SetRoomSize = "set_room_size";
		public static readonly StringName GetRoomSize = "get_room_size";
		public static readonly StringName SetSpread = "set_spread";
		public static readonly StringName GetSpread = "get_spread";
		public static readonly StringName SetWet = "set_wet";
		public static readonly StringName GetWet = "get_wet";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectReverb";

	#region Properties

	public float Damping
	{
		get => (float)_object.Get(PropertyName.Damping);
		set => _object.Set(PropertyName.Damping, value);
	}

	public float Dry
	{
		get => (float)_object.Get(PropertyName.Dry);
		set => _object.Set(PropertyName.Dry, value);
	}

	public float Hipass
	{
		get => (float)_object.Get(PropertyName.Hipass);
		set => _object.Set(PropertyName.Hipass, value);
	}

	public float PredelayFeedback
	{
		get => (float)_object.Get(PropertyName.PredelayFeedback);
		set => _object.Set(PropertyName.PredelayFeedback, value);
	}

	public float PredelayMsec
	{
		get => (float)_object.Get(PropertyName.PredelayMsec);
		set => _object.Set(PropertyName.PredelayMsec, value);
	}

	public float RoomSize
	{
		get => (float)_object.Get(PropertyName.RoomSize);
		set => _object.Set(PropertyName.RoomSize, value);
	}

	public float Spread
	{
		get => (float)_object.Get(PropertyName.Spread);
		set => _object.Set(PropertyName.Spread, value);
	}

	public float Wet
	{
		get => (float)_object.Get(PropertyName.Wet);
		set => _object.Set(PropertyName.Wet, value);
	}

	#endregion

	#region Methods

	public void SetDamping(float @damping)
	{
		_object.Call(MethodName.SetDamping, @damping);
	}

	public float GetDamping()
	{
		return (float)_object.Call(MethodName.GetDamping);
	}

	public void SetDry(float @dry)
	{
		_object.Call(MethodName.SetDry, @dry);
	}

	public float GetDry()
	{
		return (float)_object.Call(MethodName.GetDry);
	}

	public void SetHpf(float @hpf)
	{
		_object.Call(MethodName.SetHpf, @hpf);
	}

	public float GetHpf()
	{
		return (float)_object.Call(MethodName.GetHpf);
	}

	public void SetPredelayFeedback(float @predelay_feedback)
	{
		_object.Call(MethodName.SetPredelayFeedback, @predelay_feedback);
	}

	public float GetPredelayFeedback()
	{
		return (float)_object.Call(MethodName.GetPredelayFeedback);
	}

	public void SetPredelayMsec(float @predelay_msec)
	{
		_object.Call(MethodName.SetPredelayMsec, @predelay_msec);
	}

	public float GetPredelayMsec()
	{
		return (float)_object.Call(MethodName.GetPredelayMsec);
	}

	public void SetRoomSize(float @room_size)
	{
		_object.Call(MethodName.SetRoomSize, @room_size);
	}

	public float GetRoomSize()
	{
		return (float)_object.Call(MethodName.GetRoomSize);
	}

	public void SetSpread(float @spread)
	{
		_object.Call(MethodName.SetSpread, @spread);
	}

	public float GetSpread()
	{
		return (float)_object.Call(MethodName.GetSpread);
	}

	public void SetWet(float @wet)
	{
		_object.Call(MethodName.SetWet, @wet);
	}

	public float GetWet()
	{
		return (float)_object.Call(MethodName.GetWet);
	}

	#endregion
}
