// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioEffectStereoEnhance : FmodAudioEffect
{
	public FmodAudioEffectStereoEnhance() : base(NativeName)
	{
	}
	protected FmodAudioEffectStereoEnhance(StringName @class) : base(@class)
	{
	}
	protected FmodAudioEffectStereoEnhance(Variant variant) : base(variant)
	{
	}
	protected FmodAudioEffectStereoEnhance([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioEffectStereoEnhance self) => self?._object;
	public static implicit operator Variant(FmodAudioEffectStereoEnhance self) => self?._object;
	public static explicit operator FmodAudioEffectStereoEnhance(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioEffect.PropertyName
	{
		public static readonly StringName PanPullout = "pan_pullout";
		public static readonly StringName TimePulloutMs = "time_pullout_ms";
		public static readonly StringName Surround = "surround";
	}

	public new class MethodName : FmodAudioEffect.MethodName
	{
		public static readonly StringName SetPanPullout = "set_pan_pullout";
		public static readonly StringName GetPanPullout = "get_pan_pullout";
		public static readonly StringName SetTimePullout = "set_time_pullout";
		public static readonly StringName GetTimePullout = "get_time_pullout";
		public static readonly StringName SetSurround = "set_surround";
		public static readonly StringName GetSurround = "get_surround";
	}

	public new class SignalName : FmodAudioEffect.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioEffectStereoEnhance";

	#region Properties

	public float PanPullout
	{
		get => (float)_object.Get(PropertyName.PanPullout);
		set => _object.Set(PropertyName.PanPullout, value);
	}

	public float TimePulloutMs
	{
		get => (float)_object.Get(PropertyName.TimePulloutMs);
		set => _object.Set(PropertyName.TimePulloutMs, value);
	}

	public float Surround
	{
		get => (float)_object.Get(PropertyName.Surround);
		set => _object.Set(PropertyName.Surround, value);
	}

	#endregion

	#region Methods

	public void SetPanPullout(float @amount)
	{
		_object.Call(MethodName.SetPanPullout, @amount);
	}

	public float GetPanPullout()
	{
		return (float)_object.Call(MethodName.GetPanPullout);
	}

	public void SetTimePullout(float @amount)
	{
		_object.Call(MethodName.SetTimePullout, @amount);
	}

	public float GetTimePullout()
	{
		return (float)_object.Call(MethodName.GetTimePullout);
	}

	public void SetSurround(float @amount)
	{
		_object.Call(MethodName.SetSurround, @amount);
	}

	public float GetSurround()
	{
		return (float)_object.Call(MethodName.GetSurround);
	}

	#endregion
}
