// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodAudioStreamFLAC : FmodAudioStream
{
	public FmodAudioStreamFLAC() : base(NativeName)
	{
	}
	protected FmodAudioStreamFLAC(StringName @class) : base(@class)
	{
	}
	protected FmodAudioStreamFLAC(Variant variant) : base(variant)
	{
	}
	protected FmodAudioStreamFLAC([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(FmodAudioStreamFLAC self) => self?._object;
	public static implicit operator Variant(FmodAudioStreamFLAC self) => self?._object;
	public static explicit operator FmodAudioStreamFLAC(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : FmodAudioStream.PropertyName
	{

	}

	public new class MethodName : FmodAudioStream.MethodName
	{

	}

	public new class SignalName : FmodAudioStream.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodAudioStreamFLAC";
}
